// profile dimensions
rAlu = 5.5/2; // radius of centerhole
wAlu1 = 20.0; // width/height of profile
wAlu2 = 6.0; // width of slot opening
wAlu3 = 5.5; // distance from outside till core
tAlu = 2.0; // thickness of outside alu slot
rAluScrew = 5.2/2;
rAluScrewHead = 10.0/2;
Alu = 1.5;
lAluHammerNut = 11.5;
wAluHammerNut = 6.5;
rAluWasher = 10.0/2;
hAluCornerPiece = 18.0;


// related dimensions
tPlastic = 5.0;