// profile dimensions
rAlu = 5.0/2; // radius of centerhole
wAlu1 = 15.0; // width/height of profile
wAlu2 = 6.0; // width of slot opening
wAlu3 = 4.0; // distance from outside till core
tAlu = 2.0; // thickness of outside alu slot
rAluScrew = 4.0/2;
rAluScrewHead = 8.0/2; // head clearance
tAlu = 1.5;
lAluHammerNut = 11.5;
wAluHammerNut = 5.7;
rAluWasher = 10.0/2;
hAluCornerPiece = 13.0;


// related dimensions
tPlastic = 4.5;